version: '3.8'

services:
  web:
    build: .
    container_name: django5-app
    ports:
      - "8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=your_project.settings
      - PYTHONUNBUFFERED=1
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: django5-db
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432"

volumes:
  pgdata:
    driver: local
