version: '3.8'

services:
  web:
    build: .
    container_name: vuejs-app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development

# No database service needed for this basic Vue.js setup
