version: '3.8'

services:
  web:
    build: .
    container_name: astro5‑app
    ports:
      - "3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]
